version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker_on_rails
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: docker_on_rails
      MYSQL_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    environment:
      DB_NAME: docker_on_rails
      DB_USER: root
      DB_PASSWORD: rootpassword
